name: Connect to OpenVPN
on: push
jobs:
  connect-vpn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install OpenVPN
        run: sudo apt-get install openvpn
      - name: Connect VPN
        run: openvpn --config "/Vpn.File/recoreco-br1.vpnjantit-udp-2500 (1).ovpn"
