name: Connect to OpenVPN

on: push

jobs:
  connect-vpn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install OpenVPN
        run: sudo apt-get install openvpn
      - name: Check VPN config file
        run: |
          if [ -f "recoreco-br1.vpnjantit-udp-2500 (1).ovpn" ]; then
            echo "VPN config file found"
          else
            echo "VPN config file not found"
          fi
      - name: Check VPN connection
        run: |
          openvpn --status
          if [ "$?" -eq "0" ]; then
            echo "VPN connected"
          else
            echo "VPN not connected"
          fi
