name: Connect to OpenVPN

on: push

jobs:
  connect-vpn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install OpenVPN
        run: sudo apt-get install openvpn
      - name: Check VPN config file
        run: |
          if [ -f "recoreco-br1.vpnjantit-udp-2500 (1).ovpn" ]; then
            echo "VPN config file found"
          else
            echo "VPN config file not found"
          fi
      - name: Connect VPN
        env:
          VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
        run: |
          echo "${VPN_USERNAME}" > auth.txt
          echo "${VPN_PASSWORD}" >> auth.txt
          openvpn --config "recoreco-br1.vpnjantit-udp-2500 (1).ovpn" --auth-user-pass auth.txt --log openvpn.log &
          sleep 10
          cat openvpn.log
          shred -u auth.txt
      - name: Keep VPN connection active
        run: sleep 60
